[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"

[profile.default.metadata]
bytecode_hash = "ipfs"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

[doc]
out = "docs"

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.coverage]
fuzz = { runs = 10000 }
invariant = { runs = 10000 }
