[profile.default]
src = "."
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

# Remappings for dependencies
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

[doc]
out = "docs"

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.coverage]
fuzz = { runs = 10000 }
invariant = { runs = 10000 }
